language: node_js
node_js:
  - "10.7"

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.9.2
  - export PATH="$HOME/.yarn/bin:$PATH"
install:
  - yarn install
script:
  - npm run build
cache:
  yarn: true
  directories:
    - node_modules
before_deploy:
- cd ${root}
deploy:
  provider: pages
  skip-cleanup: true
  keep-history: true
  github-token: "d2839505ad1d03eb116ec3eb0309d3342d8e30a8"
  on:
    branch: master
  local-dir: dist
  target_branch: gh-pages